### ISSUE TITLE
Error: Cannot find module 'npmlog'

### ISSUE THREAD

**Issue by Semior001** [shadowcodex/c9.ide.desktop#8]
Run "c9 install c9.ide.desktop --force" starting an exception:

module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /mnt/shared/sbin/npm:18:11
    at Object.<anonymous> (/mnt/shared/sbin/npm:75:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
Command failed: /mnt/shared/sbin/npm

**Comment by Semior001** [comment]
I'm sorry, I didn't see that this issue has already arisen
I don't know how to remove this issue
